name: Ubuntu Npc

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Leave only desired OS in the field'
        required: true
        default: 'ubuntu-20.04'
        #default: 'windows-2016 | windows-2019 | ubuntu-16.04 | ubuntu-18.04 | ubuntu-20.04 | macos-10.15 | macos-11.0'
jobs:
  Instance:
    runs-on: ${{ github.event.inputs.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Run Start Npc
      uses: helenpayne/NPS-Action@master
      with:
        SSH_PASS: ${{ secrets.SSH_PASS }}
        SSH_IP: ${{ secrets.SSH_IP }}
        SSH_VKEY: ${{ secrets.SSH_VKEY }}
